version: 1.1.1.{build}
os: Visual Studio 2015
services:
- mongodb
- mssql2014
- mysql
- postgresql
install:
- cmd: nuget install redis-64 -OutputDirectory packages -excludeversion 
- cmd: packages\redis-64\tools\redis-server.exe --service-install
- cmd: packages\redis-64\tools\redis-server.exe --service-start
environment:
  NUGETKEY:
    secure: z2fJQckgBQJ7IKfjOyrZYPM2+xDj4xYuqaUDBG7MrJs+b1bNc0vzYMTxpF6Sb1mA
  COVERALLSKEY:
    secure: YoOxsHgzMZ+W0Jfa/fVvjVwHsj1GNOijRmehvrK1/6suYTgTrXsRZbshKEYOhM88
test: off    
build_script:
- cmd: build.cmd ci nugetkey=%NUGETKEY% nugetpublishurl=https://www.myget.org/F/saladlab/api/v2/package nugetprerelease=%APPVEYOR_BUILD_NUMBER% coverallskey=%COVERALLSKEY%
