version: 1.0.1.{build}
os: Visual Studio 2015
configuration: Debug
services:
- mongodb
- mssql2014
- mysql
- postgresql
install:
- cmd: nuget install redis-64 -OutputDirectory packages -excludeversion 
- cmd: packages\redis-64\tools\redis-server.exe --service-install
- cmd: packages\redis-64\tools\redis-server.exe --service-start
before_build:
- cmd: nuget restore
build:
  project: TrackableData.sln
  verbosity: minimal
environment:
  NUGETKEY:
    secure: z2fJQckgBQJ7IKfjOyrZYPM2+xDj4xYuqaUDBG7MrJs+b1bNc0vzYMTxpF6Sb1mA
deploy_script:
- cmd: build.cmd nuget nugetkey=%NUGETKEY% nugetpublishurl=https://www.myget.org/F/saladbowlcreative/api/v2/package nugetprerelease=%APPVEYOR_BUILD_NUMBER%
