// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("1.0.0")]
[assembly: AssemblyFileVersionAttribute("1.1.5")]
[assembly: AssemblyInformationalVersionAttribute("1.1.5-beta")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.0.0";
        internal const string InformationalVersion = "1.1.5-beta";
    }
}
