// <auto-generated/>
using System.Reflection;

[assembly: AssemblyVersionAttribute("1.1.1")]
[assembly: AssemblyFileVersionAttribute("1.1.1")]
[assembly: AssemblyInformationalVersionAttribute("1.1.1")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "1.1.1";
        internal const string InformationalVersion = "1.1.1";
    }
}
