// <auto-generated/>
using System;
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyTitleAttribute("TrackableData.Tests")]
[assembly: AssemblyProductAttribute("TrackableData")]
[assembly: AssemblyDescriptionAttribute(" TrackableData types can track data change and use it")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2015 Saladbowl Creative")]
[assembly: AssemblyCompanyAttribute("Saladbowl Creative")]
[assembly: ComVisibleAttribute(false)]
[assembly: CLSCompliantAttribute(false)]
[assembly: AssemblyVersionAttribute("0.1.0.0")]
[assembly: AssemblyFileVersionAttribute("0.1.0.0")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.1.0.0";
    }
}
